--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 03-02-2016 6:29:14 AM
-- Server version: 5.6.27-log
-- Client version: 4.1
--

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

SET NAMES 'utf8';


USE mis_db;


DROP TABLE IF EXISTS doctor;
CREATE TABLE doctor (
  DoctorID VARCHAR(50) NOT NULL,
  DoctorName TEXT NOT NULL,
  FatherName TEXT NOT NULL,
  Address TEXT NOT NULL,
  ContactNo TEXT NOT NULL,
  Email TEXT NOT NULL,
  Qualifications TEXT NOT NULL,
  Specialization TEXT NOT NULL,
  Gender TEXT NOT NULL,
  Bloodgroup TEXT NOT NULL,
  DateOfJoining TEXT NOT NULL,
  PRIMARY KEY (DoctorID)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS patientregistration;
CREATE TABLE patientregistration (
  PatientID VARCHAR(50) NOT NULL,
  Patientname TEXT NOT NULL,
  Fathername TEXT NOT NULL,
  Address TEXT NOT NULL,
  ContactNo TEXT NOT NULL,
  Email TEXT NOT NULL,
  Age INT(11) NOT NULL,
  Gen TEXT NOT NULL,
  BG TEXT NOT NULL,
  Remarks TEXT NOT NULL,
  PRIMARY KEY (PatientID)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS registration;
CREATE TABLE registration (
  username VARCHAR(100) NOT NULL,
  password VARCHAR(50) NOT NULL,
  NameOfUser VARCHAR(250) NOT NULL,
  ContactNo VARCHAR(15) NOT NULL,
  Email VARCHAR(250) NOT NULL,
  PRIMARY KEY (username)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS room;
CREATE TABLE room (
  RoomNo VARCHAR(50) NOT NULL,
  RoomType VARCHAR(100) NOT NULL,
  RoomCharges INT(11) NOT NULL,
  RoomStatus VARCHAR(100) NOT NULL,
  PRIMARY KEY (RoomNo)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS services;
CREATE TABLE services (
  ServiceID INT(11) NOT NULL AUTO_INCREMENT,
  ServiceName VARCHAR(250) NOT NULL,
  ServiceDate VARCHAR(50) NOT NULL,
  PatientID VARCHAR(50) NOT NULL,
  ServiceCharges INT(11) NOT NULL,
  PRIMARY KEY (ServiceID)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS ward;
CREATE TABLE ward (
  wardname VARCHAR(100) NOT NULL,
  wardtype VARCHAR(50) NOT NULL,
  NoOfBeds INT(11) NOT NULL,
  Charges INT(11) NOT NULL,
  PRIMARY KEY (wardname)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS wardboy_nurse_tbl;
CREATE TABLE wardboy_nurse_tbl (
  ID VARCHAR(50) NOT NULL,
  W_N_Name VARCHAR(250) NOT NULL,
  Category VARCHAR(250) NOT NULL,
  Address VARCHAR(250) NOT NULL,
  ContactNo VARCHAR(15) NOT NULL,
  Email VARCHAR(250) NOT NULL,
  Qualifications VARCHAR(250) NOT NULL,
  BloodGroup VARCHAR(50) NOT NULL,
  DateOfJoining VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS admitpatient_room;
CREATE TABLE admitpatient_room (
  AdmitID INT(11) NOT NULL AUTO_INCREMENT,
  PatientID VARCHAR(50) NOT NULL,
  Disease TEXT NOT NULL,
  RoomNo VARCHAR(50) NOT NULL,
  AdmitDate TEXT NOT NULL,
  DoctorID VARCHAR(50) NOT NULL,
  AP_Remarks TEXT NOT NULL,
  PRIMARY KEY (AdmitID),
  INDEX DoctorID (DoctorID),
  INDEX DoctorID_2 (DoctorID),
  INDEX PatientID (PatientID),
  INDEX RoomNo (RoomNo),
  CONSTRAINT admitpatient_room_ibfk_1 FOREIGN KEY (PatientID)
    REFERENCES patientregistration(PatientID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT admitpatient_room_ibfk_2 FOREIGN KEY (RoomNo)
    REFERENCES room(RoomNo) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT admitpatient_room_ibfk_3 FOREIGN KEY (DoctorID)
    REFERENCES doctor(DoctorID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS admitpatient_ward;
CREATE TABLE admitpatient_ward (
  AdmitID INT(11) NOT NULL AUTO_INCREMENT,
  PatientID VARCHAR(50) NOT NULL,
  Disease TEXT NOT NULL,
  Wardname VARCHAR(100) NOT NULL,
  AdmitDate TEXT NOT NULL,
  DoctorID VARCHAR(50) NOT NULL,
  AP_Remarks TEXT NOT NULL,
  PRIMARY KEY (AdmitID),
  INDEX DoctorID (DoctorID),
  INDEX PatientID (PatientID),
  INDEX Wardname (Wardname),
  CONSTRAINT admitpatient_ward_ibfk_1 FOREIGN KEY (Wardname)
    REFERENCES ward(wardname) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT admitpatient_ward_ibfk_2 FOREIGN KEY (PatientID)
    REFERENCES patientregistration(PatientID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT admitpatient_ward_ibfk_3 FOREIGN KEY (DoctorID)
    REFERENCES doctor(DoctorID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS users;
CREATE TABLE users (
  username VARCHAR(100) NOT NULL,
  user_password VARCHAR(50) NOT NULL,
  PRIMARY KEY (username),
  CONSTRAINT users_ibfk_1 FOREIGN KEY (username)
    REFERENCES registration(username) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS dischargepatient_room;
CREATE TABLE dischargepatient_room (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  AdmitID INT(11) NOT NULL,
  DischargeDate TEXT NOT NULL,
  DP_Remarks TEXT NOT NULL,
  PRIMARY KEY (ID),
  INDEX AdmitID (AdmitID),
  CONSTRAINT dischargepatient_room_ibfk_1 FOREIGN KEY (AdmitID)
    REFERENCES admitpatient_room(AdmitID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS dischargepatient_ward;
CREATE TABLE dischargepatient_ward (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  AdmitID INT(11) NOT NULL,
  DischargeDate TEXT NOT NULL,
  DP_Remarks TEXT NOT NULL,
  PRIMARY KEY (ID),
  INDEX AdmitID (AdmitID),
  CONSTRAINT dischargepatient_ward_ibfk_1 FOREIGN KEY (AdmitID)
    REFERENCES admitpatient_ward(AdmitID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS bill_room;
CREATE TABLE bill_room (
  BillNo INT(11) NOT NULL AUTO_INCREMENT,
  DischargeID INT(11) NOT NULL,
  BillingDate TEXT NOT NULL,
  NoOfDays INT(11) NOT NULL,
  RoomCharges DOUBLE NOT NULL,
  TotalRoomCharges DOUBLE NOT NULL,
  ServiceCharges DOUBLE NOT NULL,
  TotalCharges DOUBLE NOT NULL,
  PaymentMode TEXT NOT NULL,
  PaymentModeDetails TEXT NOT NULL,
  ChargesPaid DOUBLE NOT NULL,
  DueCharges DOUBLE NOT NULL,
  PRIMARY KEY (BillNo),
  INDEX DischargeID (DischargeID),
  INDEX DischargeID_2 (DischargeID),
  CONSTRAINT bill_room_ibfk_1 FOREIGN KEY (DischargeID)
    REFERENCES dischargepatient_room(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci;


DROP TABLE IF EXISTS bill_ward;
CREATE TABLE bill_ward (
  BillNo INT(11) NOT NULL AUTO_INCREMENT,
  DischargeID INT(11) NOT NULL,
  BillingDate TEXT NOT NULL,
  BedCharges DOUBLE NOT NULL,
  NoOfDays INT(11) NOT NULL,
  TotalBedCharges DOUBLE NOT NULL,
  ServiceCharges DOUBLE NOT NULL,
  TotalCharges DOUBLE NOT NULL,
  PaymentMode TEXT NOT NULL,
  PaymentModeDetails TEXT NOT NULL,
  ChargesPaid DOUBLE NOT NULL,
  DueCharges DOUBLE NOT NULL,
  PRIMARY KEY (BillNo),
  INDEX DischargeID (DischargeID),
  CONSTRAINT bill_ward_ibfk_1 FOREIGN KEY (DischargeID)
    REFERENCES dischargepatient_ward(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;


INSERT INTO doctor VALUES
('1', 'Raj Sharma', 'CM Sharma', 'Indore', '9827858191', 'raj20505@gmail.com', 'MBBS', 'Heart', 'M', 'O+', '10/11/2019');


INSERT INTO patientregistration VALUES
('P-1', 'Piyal', 'Abc', 'Indore', '123456789', 'piyal@gmail.com', 23, 'M', 'A+', '');


INSERT INTO registration VALUES
('admin', '12345', 'fahad', '01843704802', 'rjfahad44@gmail.com');


INSERT INTO room VALUES
('101', 'General', 1200, 'Vacant'),
('102', 'Deluxe', 2200, 'Vacant');


INSERT INTO services VALUES
(1, 'X-ray Test', '23/11/2019', 'P-1', 2300);


INSERT INTO ward VALUES
('A', 'General', 4, 1300),
('B', 'Special', 4, 3400);



-- Table mis_db.wardboy_nurse_tbl does not contain any data (it is empty)


INSERT INTO admitpatient_room VALUES
(1, 'P-1', 'piyal', '101', '22/11/2019', '1', '');



-- Table mis_db.admitpatient_ward does not contain any data (it is empty)


INSERT INTO users VALUES
('admin', '12345');


INSERT INTO dischargepatient_room VALUES
(1, 1, '24/11/2019', '');



-- Table mis_db.dischargepatient_ward does not contain any data (it is empty)


INSERT INTO bill_room VALUES
(1, 1, '24/11/2019', 2, 1200, 2400, 2300, 4700, 'by Cash', '', 4700, 0);



-- Table mis_db.bill_ward does not contain any data (it is empty)


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;